AWSTemplateFormatVersion: '2010-09-09'
Resources:

  MyCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - GitBucket
      - DefaultCachePolicy
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: GitBucket
            DomainName: !GetAtt GitBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: '' # Optionally, you can provide an OAI (Origin Access Identity) for private access
        DefaultCacheBehavior:
          TargetOriginId: GitBucket
          ViewerProtocolPolicy: allow-all
          CachePolicyId: !Ref DefaultCachePolicy
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        PriceClass: PriceClass_100 # Optional, to define the price class for the distribution
        Comment: My CloudFront Distribution with S3 Origin

  GitBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cloudformationbucket84352
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      WebsiteConfiguration:
        IndexDocument: index.html

  DefaultCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: git-cache-policy
        DefaultTTL: 10
        MaxTTL: 10
        MinTTL: 1
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: mydb
      AllocatedStorage: '5'
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: '{{resolve:secretsmanager:rds!db-7cd8f11f-c12d-46f9-b2d0-a29693f37822:SecretString:username}}'
      MasterUserPassword: '{{resolve:secretsmanager:rds!db-7cd8f11f-c12d-46f9-b2d0-a29693f37822:SecretString:password}}'

  MyNewServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ddc798b3f1a5117e 
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: MyNewServer

Outputs:
  CloudFrontURL:
    Value: https://drf2mowams5v2.cloudfront.net
    Description: URL of the CloudFront distribution 
