AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Type: String
    Description: The Environment being targetted
    Default: main
  Domain:
    Type: String
    Description: The Domain used for hosting
  SharedStackName:
    Type: String
    Description: The Cloudformation Stack for the Shared Infrastructure
    Default: main-shared-infrastructure
Resources:
  UIS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Environment}-ui-bucket"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      WebsiteConfiguration:
        IndexDocument: index.html
  DefaultCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "${Environment}-cf-cache-policy"
        DefaultTTL: 10
        MaxTTL: 10
        MinTTL: 1
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none
  CloudFrontCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "${Environment}.${Domain}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub "${Environment}.${Domain}"
          HostedZoneId: 
            Fn::ImportValue: !Sub "${SharedStackName}-HostedZoneId"
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - UIS3Bucket
      - DefaultCachePolicy
      - CloudFrontCertificate
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: UIS3Bucket
            DomainName: !GetAtt UIS3Bucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: UIS3Bucket
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: !Ref DefaultCachePolicy
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFrontCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        PriceClass: PriceClass_100 
        Comment: Distribution for Application UI
  ARecord01:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
         Fn::ImportValue: !Sub "${SharedStackName}-HostedZoneId"  

      Name: !Sub "${Environment}.${Domain}."
      Type: A
      AliasTarget:
        DNSName: !Sub "${CloudFrontDistribution.DomainName}."
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: true
