name: Deploy to EC2 on Merge to Main

on:
  push:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check PRIVATE_IP
        run: if [ -z "$PRIVATE_IP" ]; then echo "PRIVATE_IP is not set"; exit 1; else echo $PRIVATE_IP; fi

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$PRIVATE_IP << 'EOF'
            cd /AWS-Dummy/server
            git pull origin main
            pm2 restart main-private-host || pm2 start main-private-host
          EOF

      - name: Notify on success
        if: success()
        run: echo "Deployment to EC2 was successful."

      - name: Notify on failure
        if: failure()
        run: echo "Deployment to EC2 failed."
