name: Apply Database Migrations via Bastion Host

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH key for Bastion Host
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/bastion_key.pem
          chmod 400 /tmp/bastion_key.pem

      - name: SSH into Bastion Host and Run Database Migrations
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/bastion_key.pem ec2-user@${{ secrets.BASTION_HOST_IP }} << 'EOF'
            echo "Running migrations on PostgreSQL database"

            export DB_HOST=${{ secrets.DEV_DB_HOST }}
            export DB_PORT=${{ secrets.DEV_DB_PORT }}
            export DB_NAME=${{ secrets.DEV_DB_NAME }}
            export DB_USER=${{ secrets.DEV_DB_USER }}
            export DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}

            npx sequelize-cli db:migrate --url "postgres://${DEV_DB_USER}:${DEV_DB_PASSWORD}@${DEV_DB_HOST}:${DEV_DB_PORT}/${DEV_DB_NAME}"

            echo "Migration completed."
          EOF
        env:
          BASTION_HOST: ${{ secrets.BASTION_HOST }}
          DB_HOST: ${{ secrets.DEV_DB_HOST }}
          DB_PORT: ${{ secrets.DEV_DB_PORT }}
          DB_NAME: ${{ secrets.DEV_DB_NAME }}
          DB_USER: ${{ secrets.DEV_DB_USER }}
          DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}

      - name: Verify Migration
        run: echo "Database migration applied successfully."
